### ISSUE TITLE
failures in ec_tests from upstream testsuite

### ISSUE THREAD

**Issue by ngothan** [opencryptoki/opencryptoki#404] opened 2021-05-17 07:19 UTC
Description of problem:

5 failures are reported when running ec_tests from upstream test suite. They are present when running tests for ICA token on s390x.

Token #1 Info:
	Label: icatok                          
	Manufacturer: IBM                             
	Model: ICA             
	Serial Number:                 
	Flags: 0x880045 (RNG|LOGIN_REQUIRED|CLOCK_ON_TOKEN|USER_PIN_TO_BE_CHANGED|SO_PIN_TO_BE_CHANGED|)
	Sessions: 0/[effectively infinite]
	R/W Sessions: [information unavailable]/[effectively infinite]
	PIN Length: 4-8
	Public Memory: [information unavailable]/[information unavailable]
	Private Memory: [information unavailable]/[information unavailable]
	Hardware Version: 0.0
	Firmware Version: 0.0
	Time: 2021042902021900
```
./ec_tests  -slot 1

------
* TESTCASE run_GenerateECCKeyPairSignVerify BEGIN Starting ECC generate key pair with pkey=0 ...
* TESTCASE run_GenerateECCKeyPairSignVerify FAIL (testcases/crypto/ec_func.c:1395) C_GenerateKeyPair with valid input failed at i=0 (brainpoolP160r1), rc=CKR_FUNCTION_FAILED
------
* TESTCASE run_GenerateSignVerifyECC BEGIN Starting with mechtype='CKM_ECDSA', inputlen=20 parts=0, pkey=0
* TESTCASE run_GenerateSignVerifyECC ERROR (testcases/crypto/ec_func.c:1206)) C_Sign rc=CKR_FUNCTION_FAILED
* TESTCASE run_ImportECCKeyPairSignVerify FAIL (testcases/crypto/ec_func.c:1577) run_GenerateSignVerifyECC failed index=0.
------
* TESTCASE run_GenerateSignVerifyECC BEGIN Starting with mechtype='CKM_ECDSA', inputlen=20 parts=0, pkey=0
* TESTCASE run_GenerateSignVerifyECC ERROR (testcases/crypto/ec_func.c:1206)) C_Sign rc=CKR_FUNCTION_FAILED
* TESTCASE run_TransferECCKeyPairSignVerify FAIL (testcases/crypto/ec_func.c:1889) run_GenerateSignVerifyECC failed index=0.
------
* TESTCASE run_DeriveECDHKey BEGIN starting run_DeriveECDHKey with pkey=0 ...
* TESTCASE run_DeriveECDHKey FAIL (testcases/crypto/ec_func.c:477) C_GenerateKeyPair with valid input failed at i=0 (brainpoolP160r1), rc=CKR_FUNCTION_FAILED
------
* TESTCASE run_DeriveECDHKeyKAT BEGIN Starting with shared secret i=0, pkey=0
* TESTCASE run_DeriveECDHKeyKAT FAIL (testcases/crypto/ec_func.c:931) C_DeriveKey #1: rc = CKR_FUNCTION_FAILED
------

Total=15, Ran=9, Passed=4, Failed=5, Skipped=6, Errors=2 (total elapsed time 0s 5697us)
```
Version-Release number of selected component (if applicable):
opencryptoki-3.16.0
openssl-1:1.1.1j
libica-3.7.0

How reproducible:
always

Steps to Reproduce:
1. compile tests from SRPM file, run the test suite

Actual results:
5 failures

Expected results:
no failures

**Comment by ifranzki** [comment] 2021-05-17 07:52
Could you possibly provide the output from a run with OCK trace enabled? 
`export OPENCRYPTOKI_TRACE_LEVEL=4`

It seems to always fail when dealing with the `brainpoolP160r1` curve.  Could it be that libica does not support that curve, i.e. due to FIPS build? If the hardware does not support that curve, it might fall back to software (i.e. OpenSSL), and I have seen cases where OpenSSL also does not support certain curves (i.e. due to FIPS build).

**Comment by ngothan** [comment] 2021-05-18 17:45
@ifranzki , i'm not sure whether libica does support that curve on our s390x test machine. How can we check it?

Karel Srot from our QA team provided the whole trace file to this bug. Listed errors were
```
05/18/2021 01:44:58 399030 [usr/lib/api/apiutil.c:518 api] DEVEL: DL_Load of libpkcs11_tpm.so failed, dlerror: libpkcs11_tpm.so: cannot open shared object file: No such file or directory
05/18/2021 01:44:58 399030 [usr/lib/cca_stdll/cca_specific.c:409 ccatok] ERROR: token_specific_init: Error loading shared library 'libcsulcca.so' [(null)]
05/18/2021 01:44:58 399030 [usr/lib/api/apiutil.c:518 api] DEVEL: DL_Load of libpkcs11_ep11.so failed, dlerror: libpkcs11_ep11.so: cannot open shared object file: No such file or directory
05/18/2021 01:44:58 399030 [usr/lib/api/api_interface.c:1996 api] ERROR: Function Not Parallel
05/18/2021 01:44:58 399030 [usr/lib/api/api_interface.c:306 api] ERROR: Function Not Parallel
05/18/2021 01:44:58 399030 [usr/lib/ica_s390_stdll/ica_specific.c:4201 icatok] ERROR: ica_ec_key_generate() failed with rc=22.
05/18/2021 01:44:58 399030 [usr/lib/common/mech_ec.c:212 icatok] ERROR: Key Generation failed
05/18/2021 01:44:58 399030 [usr/lib/ica_s390_stdll/ica_specific.c:4335 icatok] ERROR: ica_ecdsa_sign() failed with rc = 22. 
05/18/2021 01:44:58 399030 [usr/lib/ica_s390_stdll/ica_specific.c:4335 icatok] ERROR: ica_ecdsa_sign() failed with rc = 22. 
05/18/2021 01:44:58 399030 [usr/lib/ica_s390_stdll/ica_specific.c:4201 icatok] ERROR: ica_ec_key_generate() failed with rc=22.
05/18/2021 01:44:58 399030 [usr/lib/common/mech_ec.c:212 icatok] ERROR: Key Generation failed
05/18/2021 01:44:58 399030 [usr/lib/ica_s390_stdll/ica_specific.c:4702 icatok] ERROR: ica_ecdh_derive_secret() failed with rc = 22. 
05/18/2021 01:44:58 399030 [usr/lib/common/mech_ec.c:955 icatok] ERROR: Token specific ecdh pkcs derive failed with rc=6.
05/18/2021 01:44:58 399030 [usr/lib/common/mech_ec.c:1140 icatok] ERROR: Error deriving the shared secret.
[root@s390x-kvm-036 crypto]#
```

For more Infos about this issue, please have a look at:
https://bugzilla.redhat.com/show_bug.cgi?id=1955551
  
[OCK trace file](https://github.com/opencryptoki/opencryptoki/files/6503250/trace.txt)

Thank so much

**Comment by ifranzki** [comment] 2021-05-19 09:54
OK, rc = 22 (EINVAL) from libica indicates that ist because the curve is not supported. 

Do you have crypto adapters available on your s390x system? You can check with `lszcrypt`. If no crypto hardware is available, then it falls back to OpenSSL. Check with `openssl ecparam -list_curves` which curves are supported by OpenSSL.

Joerg was able to reproduce this by disabling the crypto hardware on his system, so that it always takes the software fallback.  He got the same errors. There is also a fix for that, causing the ICA token to return the proper return code in such case so that the testcases don't report this as an error, see PR https://github.com/opencryptoki/opencryptoki/pull/405. Its still in review though....

**Comment by ifranzki** [comment] 2021-07-07 12:00
PR https://github.com/opencryptoki/opencryptoki/pull/405 for libica has been merged in the meantime, also commit https://github.com/opencryptoki/opencryptoki/commit/8dae6def06a155c7796d54d0230b91dbffc2bba1 "ICA: Fix libica return code handling for unsupported curves" is on the master branch of opencryptoki to handle the return codes in the ICA token. 

So this problem should be resolved now.

**Closed by ifranzki** 2021-07-07 12:00 UTC
